// XP & Level Progression Architecture
export const XP_LEVELS = [
  { level: 1, title: 'Novice Initiated', minXp: 0, maxXp: 250 },
  { level: 2, title: 'Consistent Tracker', minXp: 250, maxXp: 600 },
  { level: 3, title: 'Momentum Builder', minXp: 600, maxXp: 1100 },
  { level: 4, title: 'Habit Warrior', minXp: 1100, maxXp: 1800 },
  { level: 5, title: 'Routine Master', minXp: 1800, maxXp: 2700 },
  { level: 6, title: 'Iron Disciplinarian', minXp: 2700, maxXp: 3800 },
  { level: 7, title: 'Elite Operator', minXp: 3800, maxXp: 5000 },
  { level: 8, title: 'Legend of NewYou', minXp: 5000, maxXp: 10000 },
];

export const MOTIVATIONAL_CATEGORIES = {
  hard: {
    id: 'hard',
    title: 'Hard On-Point (Discipline)',
    icon: '🔥',
    badgeClass: 'bg-orange-fire/15 text-orange-fire border-orange-fire/40',
    description: 'Raw accountability, aggressive discipline, and unyielding focus.',
    messages: [
      "No excuses, {name}. You proved your discipline today. Unyielding focus. {streak} Days Strong.",
      "Pain is temporary, {name}. Pride is forever. 100% target execution.",
      "Champions do what is required when they don't feel like it. Outstanding work today, {name}.",
      "The iron will within you grows stronger with every completed habit."
    ]
  },
  romantic: {
    id: 'romantic',
    title: 'Romantic & Affirming',
    icon: '💖',
    badgeClass: 'bg-rose-500/15 text-rose-300 border-rose-500/40',
    description: 'Gentle, loving encouragement and heart-centered affirmations.',
    messages: [
      "You are rendering so brightly today, my love! Every small step you take makes my heart swell with pride. {streak} days of pure magic! 💕",
      "So proud of you, {name}! You bring so much light and grace to your personal growth. Keep blooming.",
      "Your dedication is beautiful to witness, {name}. Rest well knowing you gave today your all.",
      "A gentle reminder that you are capable of wonderful things. Glowing progress today!"
    ]
  },
  hype: {
    id: 'hype',
    title: 'High Energy & Hype',
    icon: '⚡',
    badgeClass: 'bg-cyan-glow/15 text-cyan-glow border-cyan-glow/40',
    description: 'Explosive energy, hype celebrations, and high momentum.',
    messages: [
      "ABSOLUTE LEGEND ALERT! {name} just destroyed today's targets! Unstoppable momentum on day {streak}! 🚀⚡",
      "BEAST MODE ACTIVATED! {name} is dominating every single habit target! Let's GOOOOO!",
      "PURE UNSTOPPABLE ENERGY! You are setting the bar higher every single day, {name}!",
      "MAXIMUM VELOCITY! Daily streak extended with total perfection!"
    ]
  },
  zen: {
    id: 'zen',
    title: 'Zen & Mindful Wisdom',
    icon: '🧘',
    badgeClass: 'bg-emerald-neon/15 text-emerald-neon border-emerald-neon/40',
    description: 'Calm, grounded wisdom, reflective peace, and harmony.',
    messages: [
      "Peaceful consistency, {name}. One breath, one step at a time. Honor your quiet strength today.",
      "Still water runs deep. Another day of mindful progress completed gracefully.",
      "Harmonious effort. You honored your commitments with clarity and poise.",
      "In quiet discipline, true mastery takes root. Be proud of today's stillness."
    ]
  }
};

export const getLevelInfo = (xp = 0) => {
  const current = XP_LEVELS.find(l => xp >= l.minXp && xp < l.maxXp) || XP_LEVELS[XP_LEVELS.length - 1];
  const xpInLevel = xp - current.minXp;
  const xpNeeded = current.maxXp - current.minXp;
  const progressPercent = Math.min(100, Math.round((xpInLevel / xpNeeded) * 100));

  return {
    level: current.level,
    title: current.title,
    minXp: current.minXp,
    maxXp: current.maxXp,
    xpInLevel,
    xpNeeded,
    progressPercent,
  };
};

// Rich Cute & Unique Core Badges Collection (HARDCORE RARITY TARGETS!)
export const CORE_BADGES = [
  // --- Level & Member Progression Badges ---
  {
    id: 'badge-lvl-2',
    title: 'Consistent Tracker',
    icon: '🐱',
    category: 'Progression',
    rarity: 'Common',
    description: 'Earn 250 XP to unlock Level 2 member tier.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 2,
  },
  {
    id: 'badge-lvl-3',
    title: 'Momentum Sprinter',
    icon: '🦊',
    category: 'Progression',
    rarity: 'Rare',
    description: 'Earn 600 XP to upgrade to Level 3: Momentum Builder.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 3,
  },
  {
    id: 'badge-lvl-4',
    title: 'Habit Warrior',
    icon: '🐻',
    category: 'Progression',
    rarity: 'Rare',
    description: 'Earn 1,100 XP to upgrade to Level 4: Habit Warrior.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 4,
  },
  {
    id: 'badge-lvl-5',
    title: 'Routine Monarch',
    icon: '👑',
    category: 'Progression',
    rarity: 'Epic',
    description: 'Earn 1,800 XP to upgrade to Level 5: Routine Master.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 5,
  },
  {
    id: 'badge-lvl-6',
    title: 'Iron Disciplinarian',
    icon: '🛡️',
    category: 'Progression',
    rarity: 'Epic',
    description: 'Earn 2,700 XP to upgrade to Level 6: Iron Disciplinarian.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 6,
  },
  {
    id: 'badge-lvl-7',
    title: 'Elite Commander',
    icon: '⚡',
    category: 'Progression',
    rarity: 'Legendary',
    description: 'Earn 3,800 XP to reach Level 7: Elite Operator.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 7,
  },
  {
    id: 'badge-lvl-8',
    title: 'Legend of Self',
    icon: '💎',
    category: 'Progression',
    rarity: 'Legendary',
    description: 'Earn 5,000 XP to ascend to Level 8: Legend of Self.',
    unlocked: false,
    reqType: 'level',
    reqTarget: 8,
  },

  // --- Streak & Momentum Badges ---
  {
    id: 'badge-streak-3',
    title: '3-Day Spark',
    icon: '🐣',
    category: 'Streak',
    rarity: 'Common',
    description: 'Maintain a 3-day active streak without skipping.',
    unlocked: false,
    reqType: 'streak',
    reqTarget: 3,
  },
  {
    id: 'badge-streak-7',
    title: '7-Day Supernova',
    icon: '🔥',
    category: 'Streak',
    rarity: 'Rare',
    description: 'Achieve a full 7-day streak of daily habits.',
    unlocked: false,
    reqType: 'streak',
    reqTarget: 7,
  },
  {
    id: 'badge-streak-30',
    title: '30-Day Hardcore Overdrive',
    icon: '🚀',
    category: 'Streak',
    rarity: 'Epic',
    description: 'Maintain a grueling 30-day continuous habit momentum streak!',
    unlocked: false,
    reqType: 'streak',
    reqTarget: 30,
  },
  {
    id: 'badge-streak-100',
    title: '100-Day Iron Titan',
    icon: '🌟',
    category: 'Streak',
    rarity: 'Legendary',
    description: 'Dominate a 100-day streak of unyielding discipline!',
    unlocked: false,
    reqType: 'streak',
    reqTarget: 100,
  },
  {
    id: 'badge-streak-365',
    title: '365-Day Immortal Legend',
    icon: '🦄',
    category: 'Streak',
    rarity: 'Mythic',
    description: 'Achieve an astonishing 365 days (1 full year) of non-stop daily routine execution!',
    unlocked: false,
    reqType: 'streak',
    reqTarget: 365,
  },

  // --- Task Target Completion Badges ---
  {
    id: 'badge-task-1',
    title: 'First Spark',
    icon: '🌱',
    category: 'Achievement',
    rarity: 'Common',
    description: 'Complete your first habit target in NewSelf.',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 1,
  },
  {
    id: 'badge-task-10',
    title: 'Habit Collector',
    icon: '🎨',
    category: 'Achievement',
    rarity: 'Common',
    description: 'Complete 10 daily habit targets.',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 10,
  },
  {
    id: 'badge-task-50',
    title: 'Routine Captain',
    icon: '🏅',
    category: 'Achievement',
    rarity: 'Rare',
    description: 'Complete 50 daily habit targets.',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 50,
  },
  {
    id: 'badge-task-100',
    title: '100 Habit Iron Discipline',
    icon: '🥊',
    category: 'Achievement',
    rarity: 'Epic',
    description: 'Complete 100 total habit targets! Pure dedication.',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 100,
  },
  {
    id: 'badge-task-250',
    title: '250 Habit Grandmaster',
    icon: '👑',
    category: 'Achievement',
    rarity: 'Legendary',
    description: 'Complete 250 habit targets across all categories!',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 250,
  },
  {
    id: 'badge-task-500',
    title: '500 Habit Mythic Titan',
    icon: '🦄',
    category: 'Achievement',
    rarity: 'Mythic',
    description: 'Conquer an astonishing 500 habit targets! Absolute peak mastery.',
    unlocked: false,
    reqType: 'completedCount',
    reqTarget: 500,
  },

  // --- Step & Distance Milestones ---
  {
    id: 'badge-steps-5k',
    title: '5k Step Stride',
    icon: '👟',
    category: 'Steps',
    rarity: 'Common',
    description: 'Complete any habit target requiring 5,000+ steps.',
    unlocked: false,
    reqType: 'stepCount',
    reqTarget: 5000,
  },
  {
    id: 'badge-steps-10k',
    title: '10k Step Conqueror',
    icon: '🏃',
    category: 'Steps',
    rarity: 'Rare',
    description: 'Complete a habit target requiring 10,000+ steps.',
    unlocked: false,
    reqType: 'stepCount',
    reqTarget: 10000,
  },
  {
    id: 'badge-steps-12k',
    title: '12k Step Lightning Titan',
    icon: '⚡',
    category: 'Steps',
    rarity: 'Epic',
    description: 'Complete a specialized habit target of 12,000+ steps!',
    unlocked: false,
    reqType: 'stepCount',
    reqTarget: 12000,
  },
  {
    id: 'badge-steps-20k',
    title: '20k Step Marathoner',
    icon: '🌌',
    category: 'Steps',
    rarity: 'Legendary',
    description: 'Conquer an epic 20,000+ step specialized challenge!',
    unlocked: false,
    reqType: 'stepCount',
    reqTarget: 20000,
  },
  {
    id: 'badge-steps-50k',
    title: '50k Step Ultra Titan',
    icon: '🐉',
    category: 'Steps',
    rarity: 'Mythic',
    description: 'Crush a monumental 50,000+ step ultra challenge!',
    unlocked: false,
    reqType: 'stepCount',
    reqTarget: 50000,
  },

  // --- Category Specific Badges ---
  {
    id: 'badge-nutr-3',
    title: 'Hydration Hero',
    icon: '💧',
    category: 'Nutrition',
    rarity: 'Common',
    description: 'Complete 3 Nutrition or Hydration habit targets.',
    unlocked: false,
    reqType: 'nutritionCount',
    reqTarget: 3,
  },
  {
    id: 'badge-nutr-25',
    title: 'Avocado Glow Master',
    icon: '🥑',
    category: 'Nutrition',
    rarity: 'Rare',
    description: 'Complete 25 clean nutrition habits.',
    unlocked: false,
    reqType: 'nutritionCount',
    reqTarget: 25,
  },
  {
    id: 'badge-nutr-100',
    title: '100 Nutrition Sovereign',
    icon: '🥗',
    category: 'Nutrition',
    rarity: 'Epic',
    description: 'Complete 100 clean nutrition & hydration habit targets!',
    unlocked: false,
    reqType: 'nutritionCount',
    reqTarget: 100,
  },
  {
    id: 'badge-zen-3',
    title: 'Mindful Panda',
    icon: '🧘',
    category: 'Mindfulness',
    rarity: 'Common',
    description: 'Complete 3 Mindfulness or meditation sessions.',
    unlocked: false,
    reqType: 'mindfulnessCount',
    reqTarget: 3,
  },
  {
    id: 'badge-zen-25',
    title: 'Zen Samurai',
    icon: '🌸',
    category: 'Mindfulness',
    rarity: 'Rare',
    description: 'Complete 25 Mindfulness & Growth habits.',
    unlocked: false,
    reqType: 'mindfulnessCount',
    reqTarget: 25,
  },
  {
    id: 'badge-zen-100',
    title: '100 Zen Grand Master',
    icon: '🔮',
    category: 'Mindfulness',
    rarity: 'Epic',
    description: 'Complete 100 Mindfulness & Growth meditation habits!',
    unlocked: false,
    reqType: 'mindfulnessCount',
    reqTarget: 100,
  },

  // --- Photo & Verification Proof Badges (HARDCORE TARGETS) ---
  {
    id: 'badge-proof-1',
    title: 'Snap Initiate',
    icon: '📸',
    category: 'Verification',
    rarity: 'Common',
    description: 'Submit your 1st photo or screenshot proof for verification.',
    unlocked: false,
    reqType: 'approvedProofs',
    reqTarget: 1,
  },
  {
    id: 'badge-proof-25',
    title: 'Proof Enthusiast',
    icon: '✨',
    category: 'Verification',
    rarity: 'Rare',
    description: 'Get 25 photo proofs verified and approved by Admin.',
    unlocked: false,
    reqType: 'approvedProofs',
    reqTarget: 25,
  },
  {
    id: 'badge-proof-100',
    title: '100 Proof Epic Master',
    icon: '💎',
    category: 'Verification',
    rarity: 'Epic',
    description: 'Submit and get 100 verified photo proof images approved by Admin!',
    unlocked: false,
    reqType: 'approvedProofs',
    reqTarget: 100,
  },
  {
    id: 'badge-proof-250',
    title: '250 Proof Legendary Verifier',
    icon: '👑',
    category: 'Verification',
    rarity: 'Legendary',
    description: 'Get 250 verified photo proofs approved by Admin! Outstanding proof discipline.',
    unlocked: false,
    reqType: 'approvedProofs',
    reqTarget: 250,
  },
  {
    id: 'badge-proof-500',
    title: '500 Image Mythic Camera Titan',
    icon: '🦄',
    category: 'Verification',
    rarity: 'Mythic',
    description: 'Achieve an astounding 500+ verified proof images approved by Admin!',
    unlocked: false,
    reqType: 'approvedProofs',
    reqTarget: 500,
  },
];


